build:
  image: smlsunxie/picklete_env
  extends:
    file: ./dockerConfig/development.yml
    service: build

  working_dir: /picklete
  volumes:
    - ./:/picklete

  restart: always

web:
  image: smlsunxie/picklete_env
  extends:
    file: ./dockerConfig/development.yml
    service: web

  links:
    - mysql

  working_dir: /picklete
  volumes:
    - ./:/picklete

  restart: always

frontend:
  extends:
    file: ./dockerConfig/development.yml
    service: frontend

  image: iojs
  working_dir: /app
  restart: always


mysql:
  image: dgraziotin/mysql
  extends:
    file: ./dockerConfig/development.yml
    service: mysql
  volumes:
    - ../database:/var/lib/mysql/

  restart: always
